### ISSUE TITLE
Network performance workflow

### ISSUE THREAD

**Issue by ghost** [arcalot/arcaflow-workflows#1]
## Please describe what you would like to see in this project

We need a reusable workflow that measures network performance using UPerf and stores data in ElasticSearch.

## Work items

- [ ] Input specification
- [ ] Steps specification
- [ ] ElasticSearch data schema

**Comment by dustinblack** [comment]
At the top level, starting with the existing [data-plane test configuration](https://github.com/cloud-bulldozer/airflow-kubernetes/blob/master/dags/openshift_nightlies/config/benchmarks/data-plane.json) from the [airflow-kubernetes repo](https://github.com/cloud-bulldozer/airflow-kubernetes), we see that the [network-perf](https://github.com/cloud-bulldozer/e2e-benchmarking/tree/master/workloads/network-perf) workload from [e2e-benchmarking](https://github.com/cloud-bulldozer/e2e-benchmarking) is called with variations to the "[WORKLOAD](https://github.com/cloud-bulldozer/airflow-kubernetes/blob/efcffa627ea2ecd29822e7ad89794b95dee3c60d/dags/openshift_nightlies/config/benchmarks/data-plane.json#L8)" and the "[PAIRS](https://github.com/cloud-bulldozer/airflow-kubernetes/blob/efcffa627ea2ecd29822e7ad89794b95dee3c60d/dags/openshift_nightlies/config/benchmarks/data-plane.json#L9)" parameters. These are passed from airflow-kubernetes to e2e-benchmarking as environment variables.

```json
        {
            "name": "host-network",
            "workload": "network-perf",
            "command": "./run.sh",
            "env": {
                "WORKLOAD": "hostnet",
                "PAIRS": "1"
            }
        },
```

So let's start with those parameters as list items for the top-level input schema:

```yaml
uperf_workflows:
    - workflow:
        workload: "hostnet"
        pairs: 1

    - workflow:
        workload: "pod2pod"

    - workflow:
        workload: "pod2svc"
```

From the e2e scripts for network-perf, we find a number of [environment variable defaults](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/71651bb9d80e6a15910b2e92721d5b8e37144e91/workloads/network-perf/env.sh#L13-L23) set. We should add a defaults section to our input schema.

```yaml
uperf_workloads:
    - workflow_defaults:
        workload: "smoke"
        network_policy: False
        multi_az: True
        hostnetwork: False
        serviceip: False
        addresspool: "addresspool-l2"
        service_etp: "Cluster"
        test_timeout: 7200
        samples: 3
        pairs:
            - 1
            - 2
            - 4
```

There are also a number of environment variables that constitute global parameters that should apply outside of the workload definitions (including things we will clearly handle with other plugins). There are additional global variables in the [common.sh](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/71651bb9d80e6a15910b2e92721d5b8e37144e91/workloads/network-perf/common.sh#L12-L14) script that don't have defaults and will need to be provided.

```yaml
global_params:
    es_server: "https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443"
    metadata_collection: True
    metadata_targeted: False
    system_metrics_collection: False
    uuid: <some kind of generated uuid method>
    cluster_name: <currently done with $(oc get infrastructure cluster -o jsonpath="{.status.infrastructureName}")>
    prom_token: <currently done with $(oc sa get-token -n openshift-monitoring prometheus-k8s || oc sa new-token -n openshift-monitoring prometheus-k8s || oc create token -n openshift-monitoring  prometheus-k8s)
  nodes=($(oc get nodes -l node-role.kubernetes.io/worker,node-role.kubernetes.io/workload!="",node-role.kubernetes.io/infra!="" -o custom-columns=name:{.metadata.name} --no-headers))>
```

Now we find in the [run.sh](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/master/workloads/network-perf/run.sh) script that there are [dependency defaults](https://github.com/cloud-bulldozer/e2e-benchmarking/blob/71651bb9d80e6a15910b2e92721d5b8e37144e91/workloads/network-perf/run.sh#L7-L26), where based on one provided param we set other params.


TO BE CONTINUED...
